### ISSUE TITLE
[Feature Request] More giveaway bots

### ISSUE THREAD

**Issue by ARSHGAMER** [eternal404/nitro-sniper#355] opened 2022-02-08 15:40 UTC
### Is your feature request related to a problem?

Its not a problem but most of the server use different giveaway bots like frisky,santa etc

### Describe the solution you'd like

Add support for multiple discord bots 

### How will this be beneficial to the sniper

It will be good if this feather get added into the sniper as it will increase the sniper usage and it will improve the sniper.

### Please provide an example of usage of this feature

Giveaways mostly

**Comment by eternal404** [comment] 2022-02-08 17:13
Duplicate of #152

**Closed by eternal404** 2022-02-08 17:13 UTC
Labels: enhancement
